version: "3.8"

services:
  app:
    build: .
    container_name: goVault-container
    command: ./goVault
    ports:
      - "1234:1234"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: goVault-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: goVault-adminer
    ports:
      - "9000:9000"
    depends_on:
      - db
